.SUFFIXES: .ASM .REL

.ASM.REL:
	/Users/tchv/.cargo/bin/M80 '=$< /I/L'
	
E0MAIN.REL: E0MAIN.ASM E0DISP.MAC RK86.MAC E0BREAK.MAC

E0DISP.REL: E0DISP.ASM E0DISP.MAC

#ESC80.REL: E0MAIN.ASM E0FILEIO.ASM E0CMDT.ASM E0GETC.ASM E0DISP.ASM
clean:
	rm *.REL
	rm *.PRN
#bin: ESC80.REL
#	/Users/tchv/.cargo/bin/L80 /P:100,ESC80,ESC80.BIN/N/E/Y #Writeout to ESC80.BIN
all: HEADER.REL E0MAIN.REL E0FILEIO.REL E0CMDT.REL E0GETC.REL E0DISP.REL
	/Users/tchv/.cargo/bin/L80 /P:104,HEADER,E0MAIN,E0FILEIO,E0CMDT,E0GETC,E0DISP,ESC80.RK/N/E/Y #Writeout to ESC80.RK
	cp ESC80.RK bin/ESC80.rk
