.SUFFIXES: .ASM .REL

.ASM.REL:
	./M80 '=$< /I/L'
	
ALL: HEADER.REL E0CMDT.REL E0GETC.REL E0MAIN.REL E0DISP.REL
	./L80 /P:104,HEADER,E0MAIN,E0CMDT,E0GETC,E0DISP,E80/N/E/Y #Writeout to E80.COM
	cp E80.COM e80.rk
clean:
	rm *.REL
	rm *.PRN